#!/usr/bin/env npx tsx

/**
 * Gate for the Level-1 container fixture corpus (the document track's front door).
 *
 * This gate proves the committed corpus is coherent and the reference reader is
 * capable; the end-to-end VERDICT evaluation (does the reader disposition each
 * case correctly?) is check:conformance, which runs the adapter over the same
 * fixtures. Here we assert:
 *
 *   1. Round-trip: every committed case.json and case.cdx byte-equals what the
 *      source of truth (fixture-corpus.ts) regenerates — a drifted or hand-edited
 *      fixture fails. Mirrors the vector byte round-trip gate.
 *   2. Schema: every committed case.json validates against fixtures.schema.json.
 *   3. No orphans: every committed case directory maps to a corpus case.
 *   4. Reader codes: every code zip-reader.ts can emit is registered in errors.json.
 *   5. Deflate support: method 8 round-trips in-memory with a verified CRC (proving
 *      the mandatory algorithm works WITHOUT committing a non-deterministic archive).
 *   6. Independent oracle: archive_oracle.py confirms each malformation is actually
 *      present in the committed bytes.
 */

import * as fs from 'fs';
import * as path from 'path';
import { execFileSync } from 'child_process';
import { createAjv } from './lib/ajv-utils.js';
import { FIXTURE_CORPUS, caseJson } from './lib/fixture-corpus.js';
import { buildZip } from './lib/zip-writer.js';
import { readArchive, crcMatches, CODE } from './lib/zip-reader.js';
import { isRegisteredCode } from './lib/error-codes.js';
import { isWellFormedInterval } from './lib/disposition.js';

const CONF = path.join(__dirname, '..', 'conformance');
const KIND = 'container';
const root = path.join(CONF, 'fixtures', KIND);

let failures = 0;
const fail = (m: string): void => { console.log(`  ✗ ${m}`); failures++; };
const ok = (m: string): void => console.log(`  ✓ ${m}`);

// 1-3. Round-trip, schema, orphans.
console.log('Fixture corpus integrity:');
const schema = JSON.parse(fs.readFileSync(path.join(CONF, 'fixtures', 'fixtures.schema.json'), 'utf8'));
const validateCase = createAjv().compile(schema) as ((x: unknown) => boolean) & { errors?: unknown };

let rtOk = true;
let schemaOk = true;
for (const c of FIXTURE_CORPUS) {
  const dir = path.join(root, c.name);
  const caseFile = path.join(dir, 'case.json');
  const cdxFile = path.join(dir, 'case.cdx');
  if (!fs.existsSync(caseFile) || !fs.existsSync(cdxFile)) {
    fail(`${c.name}: missing case.json or case.cdx — run \`npm run build:fixtures\``);
    rtOk = false;
    continue;
  }
  if (fs.readFileSync(caseFile, 'utf8') !== caseJson(c)) {
    fail(`${c.name}: committed case.json != regenerated — run \`npm run build:fixtures\``);
    rtOk = false;
  }
  if (Buffer.compare(fs.readFileSync(cdxFile), buildZip(c.recipe)) !== 0) {
    fail(`${c.name}: committed case.cdx != buildZip(recipe) — run \`npm run build:fixtures\``);
    rtOk = false;
  }
  if (!validateCase(JSON.parse(fs.readFileSync(caseFile, 'utf8')))) {
    fail(`${c.name}: case.json fails fixtures.schema.json: ${JSON.stringify(validateCase.errors)}`);
    schemaOk = false;
  }
}
if (rtOk) ok(`all ${FIXTURE_CORPUS.length} fixtures round-trip (committed == regenerated bytes)`);
if (schemaOk) ok(`all ${FIXTURE_CORPUS.length} case.json validate against fixtures.schema.json`);

const corpusNames = new Set(FIXTURE_CORPUS.map((c) => c.name));
const orphans = fs.existsSync(root)
  ? fs.readdirSync(root).filter((d) => fs.statSync(path.join(root, d)).isDirectory() && !corpusNames.has(d))
  : [];
if (orphans.length === 0) ok('no orphan fixture directories');
else fail(`orphan fixture directories not in corpus: ${orphans.join(', ')}`);

// Interval sanity: an authored interval must have atLeast <= atMost. The schema
// checks each bound is a disposition but not their ordering, so an inverted
// interval would silently make a case unpassable (inInterval always false).
let intervalOk = true;
for (const c of FIXTURE_CORPUS) {
  const bad: string[] = [];
  if (!isWellFormedInterval(c.expect.documentDisposition)) bad.push('documentDisposition');
  for (const f of c.expect.findings) if (!isWellFormedInterval(f)) bad.push(f.code);
  if (bad.length > 0) {
    fail(`${c.name}: inverted disposition interval(s): ${bad.join(', ')}`);
    intervalOk = false;
  }
}
if (intervalOk) ok(`all ${FIXTURE_CORPUS.length} fixtures have well-formed disposition intervals`);

// 4. Reader codes registered.
console.log('\nReader defect codes:');
const codes = Object.values(CODE);
const unreg = codes.filter((c) => !isRegisteredCode(c));
if (unreg.length === 0) ok(`all ${codes.length} reader codes registered in errors.json`);
else fail(`reader codes not registered in errors.json: ${unreg.join(', ')}`);

// 5. Deflate support (in-memory; never committed, since deflate bytes are not
//    guaranteed stable across zlib builds).
console.log('\nCompression support:');
{
  // Name the sole entry manifest.json so the first-file check (Container 4.2) is satisfied.
  const bytes = buildZip({ entries: [{ name: 'manifest.json', text: 'x'.repeat(4000) + ' hello world', method: 'deflate' }] });
  const r = readArchive(bytes);
  if (r.findings.length === 0 && r.entries.length === 1 && crcMatches(bytes, r.entries[0])) {
    ok('Deflate (method 8) round-trips in memory with CRC verified');
  } else {
    fail(`Deflate support self-test failed: findings=${JSON.stringify(r.findings.map((f) => f.code))}`);
  }
}

// 6. Independent oracle: defect-presence in the committed bytes.
console.log('\nIndependent archive oracle (python3, defect-presence):');
try {
  const out = execFileSync('python3', [path.join(CONF, 'oracles', 'archive_oracle.py'), 'check'], { encoding: 'utf8' });
  process.stdout.write(out.replace(/^/gm, '  '));
} catch (err) {
  const e = err as { stdout?: string; stderr?: string; message?: string };
  if (e.stdout) process.stdout.write(e.stdout.replace(/^/gm, '  '));
  if (e.stderr) process.stdout.write(e.stderr.replace(/^/gm, '  '));
  fail(`archive_oracle.py check failed${e.message ? `: ${e.message}` : ''}`);
}

if (failures > 0) {
  console.log(`\n${failures} failure(s). Fixture check failed.`);
  process.exit(1);
}
console.log('\nContainer fixture corpus verified.');
